version: '3.8'

services:
  dibimbing-dataeng-postgres:
    image: postgres:11
    container_name: ${DIBIMBING_DE_POSTGRES_CONTAINER_NAME}
    restart: unless-stopped
    hostname: ${DIBIMBING_DE_POSTGRES_HOST}
    networks:
      - dibimbing-dataeng-network
    environment:
      - POSTGRES_PASSWORD=${DIBIMBING_DE_POSTGRES_PASSWORD}
      - POSTGRES_USER=${DIBIMBING_DE_POSTGRES_ACCOUNT}
      - POSTGRES_DB=${DIBIMBING_DE_POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../challenge_sql:/challenge_sql
      - ../challenge_spark:/challenge_spark
      - ../data:/data
    ports:
      - ${DIBIMBING_DE_POSTGRES_PORT}:5432

networks:
  dibimbing-dataeng-network:
    driver: bridge
    external: true
