version: '2'

services:
  dibimbing-dataeng-spark-master:
    container_name: ${DIBIMBING_DE_SPARK_MASTER_CONTAINER_NAME}
    hostname: ${DIBIMBING_DE_SPARK_MASTER_HOST_NAME}
    image: dataeng-dibimbing/challenges_spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ../challenge_spark:/challenge_spark
      - ../source_data:/source_data
    ports:
      - '8100:8080'
      - '7077:7077'

  dibimbing-dataeng-spark-worker-1:
    &worker_default
    container_name: ${DIBIMBING_DE_SPARK_WORKER_CONTAINER_NAME}-1
    image: dataeng-dibimbing/challenges_spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://${DIBIMBING_DE_SPARK_MASTER_HOST_NAME}:${DIBIMBING_DE_SPARK_MASTER_PORT}
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ../challenge_spark:/challenge_spark
      - ../source_data:/source_data
    depends_on:
      - dibimbing-dataeng-spark-master

  dibimbing-dataeng-spark-worker-2:
    <<: *worker_default
    container_name: ${DIBIMBING_DE_SPARK_WORKER_CONTAINER_NAME}-2

networks:
  default:
    name: dibimbing-dataeng-network
